# -*- coding: utf-8 -*-
"""1d ideal thrust calculator solid

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IKMkMMU8lFU8mZUBjrC0xfY2RQGg4Kvl
"""

import math

# Constants
g0 = 9.81  # m/s^2

# Inputs
Tc = 1820       # chamber temperature (K)
gamma = 1.16
R = 225         # J/(kg*K) typical combustion gas
At = 0.000010      # throat area (m^2)
Pa = 101325     # ambient pressure (Pa)
Ae = 0.000040      # exit area (m^2)

# Propellant properties
a_Mpa = .06       # burn rate coefficient (m/s/Pa^n)
n = .3       # burn rate exponent
Pp = 1900      # propellant density (kg/m^3)
# Grain geometry
L = .05 # grain length in meters
r_core = .003 # radios of hollow core in meters 
Ro = .009 # radius of grain edge touching the case in meters

#define time steps 
t = 0
dt = .01

#store data for graph
time_data = []
thrust_data = []
pressure_data = []

# convert a to from MPa to Pa
a = a_Mpa/(1000000**n)
#start sim loop
while r_core < Ro:
    Ab = (2* math.pi * r_core *L)     # burning surface area (m^2)
#check for ratio issues
    if Ae<At:
        print("Error: Exit area must be greater than throat area for supersonic flow.")
# refine Me
    else:# solve for mach exit number (roughly)
# rough starting point
        Me = 3.0
        area_ratio = Ae/At

        for _ in range(10):
            f = (1/Me) * ((2/(gamma+1)) * (1 + (gamma-1)/2 * Me**2))**((gamma+1)/(2*(gamma-1))) - area_ratio
            df = (f + area_ratio) *(Me**2 - 1) / (Me * (1 + (gamma -1) / 2 * Me**2))
            Me = abs(Me - f/df)
#check flow type
            if Me >1.0:
                flow_type = "supersonic"
            elif Me ==  1.0:
                flow_type = "sonic (choked)"
            else:
                flow_type = "subsonic"

# solve for C
        C = math.sqrt(gamma/(R*Tc))*(2/(gamma + 1))**((gamma + 1)/(2*(gamma - 1)))

# solve for chamber pressure
        Pc = (((Pp*Ab*a*(1/C) )/ At)**(1/(1-n)))

#solve for exit pressure
        Pe = Pc*((1 + ((gamma - 1)/2)*(Me**2))**(-gamma/(gamma - 1)))

#burn rate
        Rb = a*(Pc**n)

# Exhaust velocity
        ve = math.sqrt(
            (2 * gamma / (gamma - 1)) * R * Tc *
            (1 - (Pe / Pc) ** ((gamma - 1) / gamma))
        )

# Mass flow rate (generated)
        Mdot = (
            Pp*Ab*Rb
        )

# Mass flow rate (throat)/(choked flow)
        Mtdot = ((At * Pc) * math.sqrt(gamma / (R * Tc))*(2 / (gamma + 1))** ((gamma +1)/(2*(gamma -1))) )

# Thrust
        thrust = (Mdot * ve) + (Pe - Pa)*Ae

#thrust in pounds of force
        thrust_lbf = thrust/4.44822
# Specific impulse
        Isp = thrust / (Mdot*g0)

#store data for graph
        time_data.append(t)
        thrust_data.append(thrust)
        pressure_data.append(Pc/1e6) #keep in MPa for graph 

#advance time and grain geometry
        r_core = r_core + (Rb*dt)
        t = t + dt
# Output
print(f"Exhaust velocity: {ve:.1f} m/s")
print(f"Thrust: {thrust:.1f} N ({thrust_lbf:.1f} lbf)")
print(f"Specific impulse: {Isp:.1f} s")
print(f"Chamber Pressure: {Pc/1e6:.2f} MPa")
# mach number and flow type
print(f" The flow type is {flow_type} with an exit mach number of {Me:.2f}")
print(f"Exit Pressure: {Pe/1e3:.2f} kPa")
# simulation output
print(f"burn complete. total burn time: {t:.2f} seconds")

# genrate graphs
import matplotlib.pyplot as plt

#create the figure
plt.figure(figsize = (10,6))

# plot axises ( trhust over time)
plt.plot (time_data, thrust_data, label = "Thrust (N)", color = "red", linewidth = 2)

#format graph
plt.title( "Motor Thrust Curve", fontsize  = 14, fontweight = "bold")
plt.xlabel("Time (s)", fontsize = 12)
plt.ylabel("Thrust (N)", fontsize = 12)
plt.grid(True, linestyle = "--", alpha = 0.7)
plt.axhline(0, color = "black", linewidth = 0.1)
plt.xlim(left = 0)
plt.ylim(bottom = 0)
plt.legend()

#show graph
plt.show()